// Generated by CoffeeScript 1.6.3
(function() {
  var hoveredProject, lzld, onProjectVisible, projects, projectsContainer;

  projects = $(".projects-project");

  projects.each(function(i, element) {
    var project, spinner;
    spinner = new Spinner({
      color: 'white'
    });
    spinner.spin(element);
    project = $(element);
    return project.data({
      spinner: spinner
    });
  });

  onProjectVisible = function(element) {
    var backgroundImage, image, project;
    project = $(element);
    backgroundImage = project.data('backgroundImage');
    if (backgroundImage) {
      image = new Image();
      image.onload = function() {
        var spinner;
        project.addClass('is-loaded');
        project.css({
          opacity: 0,
          backgroundImage: "url('" + backgroundImage + "')"
        });
        project.animate({
          opacity: 1
        }, 500, function() {});
        spinner = project.data('spinner');
        return spinner.stop();
      };
      return image.src = backgroundImage;
    }
  };

  projectsContainer = $(".projects");

  lzld = lazyload({
    container: projectsContainer[0],
    src: onProjectVisible
  });

  hoveredProject = null;

  projects.each(function(i, element) {
    var projectLink;
    lzld(element);
    if (this.Touch != null) {
      projectLink = project.children('a');
      return projectLink.click(function(event) {
        if (hoveredProject !== project) {
          event.preventDefault();
        }
        return hoveredProject = project;
      });
    }
  });

}).call(this);

/*
//@ sourceMappingURL=projects.map
*/
